package com.devtotti;

import java.util.HashMap;
import java.util.Map;

public class CurrencyCodes {
    private final Map<String, String> currencyCodes = new HashMap<>();

    public CurrencyCodes() {
        currencyCodes.put("USD", "United States Dollar");
        currencyCodes.put("AED", "United Arab Emirates Dirham");
        currencyCodes.put("AFN", "Afghan Afghani");
        currencyCodes.put("ALL", "Albanian Lek");
        currencyCodes.put("AMD", "Armenian Dram");
        currencyCodes.put("ANG", "Netherlands Antillean Guilder");
        currencyCodes.put("AOA", "Angolan Kwanza");
        currencyCodes.put("ARS", "Argentine Peso");
        currencyCodes.put("AUD", "Australian Dollar");
        currencyCodes.put("AWG", "Aruban Florin");
        currencyCodes.put("AZN", "Azerbaijani Manat");
        currencyCodes.put("BAM", "Bosnia and Herzegovina Convertible Mark");
        currencyCodes.put("BBD", "Barbadian Dollar");
        currencyCodes.put("BDT", "Bangladeshi Taka");
        currencyCodes.put("BGN", "Bulgarian Lev");
        currencyCodes.put("BHD", "Bahraini Dinar");
        currencyCodes.put("BIF", "Burundian Franc");
        currencyCodes.put("BMD", "Bermudian Dollar");
        currencyCodes.put("BND", "Brunei Dollar");
        currencyCodes.put("BOB", "Bolivian Boliviano");
        currencyCodes.put("BRL", "Brazilian Real");
        currencyCodes.put("BSD", "Bahamian Dollar");
        currencyCodes.put("BTN", "Bhutanese Ngultrum");
        currencyCodes.put("BWP", "Botswana Pula");
        currencyCodes.put("BYN", "Belarusian Ruble");
        currencyCodes.put("BZD", "Belize Dollar");
        currencyCodes.put("CAD", "Canadian Dollar");
        currencyCodes.put("CDF", "Congolese Franc");
        currencyCodes.put("CHF", "Swiss Franc");
        currencyCodes.put("CLP", "Chilean Peso");
        currencyCodes.put("CNY", "Chinese Renminbi");
        currencyCodes.put("COP", "Colombian Peso");
        currencyCodes.put("CRC", "Costa Rican Colón");
        currencyCodes.put("CUP", "Cuban Peso");
        currencyCodes.put("CVE", "Cape Verdean Escudo");
        currencyCodes.put("CZK", "Czech Koruna");
        currencyCodes.put("DJF", "Djiboutian Franc");
        currencyCodes.put("DKK", "Danish Krone");
        currencyCodes.put("DOP", "Dominican Peso");
        currencyCodes.put("DZD", "Algerian Dinar");
        currencyCodes.put("EGP", "Egyptian Pound");
        currencyCodes.put("ERN", "Eritrean Nakfa");
        currencyCodes.put("ETB", "Ethiopian Birr");
        currencyCodes.put("EUR", "Euro");
        currencyCodes.put("FJD", "Fijian Dollar");
        currencyCodes.put("FKP", "Falkland Islands Pound");
        currencyCodes.put("FOK", "Faroese Króna");
        currencyCodes.put("GBP", "British Pound");
        currencyCodes.put("GEL", "Georgian Lari");
        currencyCodes.put("GGP", "Guernsey Pound");
        currencyCodes.put("GHS", "Ghanaian Cedi");
        currencyCodes.put("GIP", "Gibraltar Pound");
        currencyCodes.put("GMD", "Gambian Dalasi");
        currencyCodes.put("GNF", "Guinean Franc");
        currencyCodes.put("GTQ", "Guatemalan Quetzal");
        currencyCodes.put("GYD", "Guyanese Dollar");
        currencyCodes.put("HKD", "Hong Kong Dollar");
        currencyCodes.put("HNL", "Honduran Lempira");
        currencyCodes.put("HRK", "Croatian Kuna");
        currencyCodes.put("HTG", "Haitian Gourde");
        currencyCodes.put("HUF", "Hungarian Forint");
        currencyCodes.put("IDR", "Indonesian Rupiah");
        currencyCodes.put("ILS", "Israeli Shekel");
        currencyCodes.put("IMP", "Isle of Man Pound");
        currencyCodes.put("INR", "Indian Rupee");
        currencyCodes.put("IQD", "Iraqi Dinar");
        currencyCodes.put("IRR", "Iranian Rial");
        currencyCodes.put("ISK", "Icelandic Króna");
        currencyCodes.put("JEP", "Jersey Pound");
        currencyCodes.put("JMD", "Jamaican Dollar");
        currencyCodes.put("JOD", "Jordanian Dinar");
        currencyCodes.put("JPY", "Japanese Yen");
        currencyCodes.put("KES", "Kenyan Shilling");
        currencyCodes.put("KGS", "Kyrgyzstani Som");
        currencyCodes.put("KHR", "Cambodian Riel");
        currencyCodes.put("KID", "Kiribati Dollar");
        currencyCodes.put("KMF", "Comorian Franc");
        currencyCodes.put("KRW", "South Korean Won");
        currencyCodes.put("KWD", "Kuwaiti Dinar");
        currencyCodes.put("KYD", "Cayman Islands Dollar");
        currencyCodes.put("KZT", "Kazakhstani Tenge");
        currencyCodes.put("LAK", "Lao Kip");
        currencyCodes.put("LBP", "Lebanese Pound");
        currencyCodes.put("LKR", "Sri Lankan Rupee");
        currencyCodes.put("LRD", "Liberian Dollar");
        currencyCodes.put("LSL", "Lesotho Loti");
        currencyCodes.put("LYD", "Libyan Dinar");
        currencyCodes.put("MAD", "Moroccan Dirham");
        currencyCodes.put("MDL", "Moldovan Leu");
        currencyCodes.put("MGA", "Malagasy Ariary");
        currencyCodes.put("MKD", "Macedonian Denar");
        currencyCodes.put("MMK", "Myanmar Kyat");
        currencyCodes.put("MNT", "Mongolian Tögrög");
        currencyCodes.put("MOP", "Macanese Pataca");
        currencyCodes.put("MRU", "Mauritanian Ouguiya");
        currencyCodes.put("MUR", "Mauritian Rupee");
        currencyCodes.put("MVR", "Maldivian Rufiyaa");
        currencyCodes.put("MWK", "Malawian Kwacha");
        currencyCodes.put("MXN", "Mexican Peso");
        currencyCodes.put("MYR", "Malaysian Ringgit");
        currencyCodes.put("MZN", "Mozambican Metical");
        currencyCodes.put("NAD", "Namibian Dollar");
        currencyCodes.put("NGN", "Nigerian Naira");
        currencyCodes.put("NIO", "Nicaraguan Córdoba");
        currencyCodes.put("NOK", "Norwegian Krone");
        currencyCodes.put("NPR", "Nepalese Rupee");
        currencyCodes.put("NZD", "New Zealand Dollar");
        currencyCodes.put("OMR", "Omani Rial");
        currencyCodes.put("PAB", "Panamanian Balboa");
        currencyCodes.put("PEN", "Peruvian Sol");
        currencyCodes.put("PGK", "Papua New Guinean Kina");
        currencyCodes.put("PHP", "Philippine Peso");
        currencyCodes.put("PKR", "Pakistani Rupee");
        currencyCodes.put("PLN", "Polish Złoty");
        currencyCodes.put("PYG", "Paraguayan Guarani");
        currencyCodes.put("QAR", "Qatari Riyal");
        currencyCodes.put("RON", "Romanian Leu");
        currencyCodes.put("RSD", "Serbian Dinar");
        currencyCodes.put("RUB", "Russian Ruble");
        currencyCodes.put("RWF", "Rwandan Franc");
        currencyCodes.put("SAR", "Saudi Riyal");
        currencyCodes.put("SBD", "Solomon Islands Dollar");
        currencyCodes.put("SCR", "Seychellois Rupee");
        currencyCodes.put("SDG", "Sudanese Pound");
        currencyCodes.put("SEK", "Swedish Krona");
        currencyCodes.put("SGD", "Singapore Dollar");
        currencyCodes.put("SHP", "Saint Helena Pound");
        currencyCodes.put("SLE", "Sierra Leonean Leone");
        currencyCodes.put("SLL", "Sierra Leonean Leone");
        currencyCodes.put("SOS", "Somali Shilling");
        currencyCodes.put("SRD", "Surinamese Dollar");
        currencyCodes.put("SSP", "South Sudanese Pound");
        currencyCodes.put("STN", "São Tomé and Principe Dobra");
        currencyCodes.put("SYP", "Syrian Pound");
        currencyCodes.put("SZL", "Swazi Lilangeni");
        currencyCodes.put("THB", "Thai Baht");
        currencyCodes.put("TJS", "Tajikistani Somoni");
        currencyCodes.put("TMT", "Turkmenistan Manat");
        currencyCodes.put("TND", "Tunisian Dinar");
        currencyCodes.put("TOP", "Tongan Paʻanga");
        currencyCodes.put("TRY", "Turkish Lira");
        currencyCodes.put("TTD", "Trinidad and Tobago Dollar");
        currencyCodes.put("TVD", "Tuvaluan Dollar");
        currencyCodes.put("TWD", "Taiwanese Dollar");
        currencyCodes.put("TZS", "Tanzanian Shilling");
        currencyCodes.put("UAH", "Ukrainian Hryvnia");
        currencyCodes.put("UGX", "Ugandan Shilling");
        currencyCodes.put("UYU", "Uruguayan Peso");
        currencyCodes.put("UZS", "Uzbekistan Som");
        currencyCodes.put("VES", "Venezuelan Bolívar");
        currencyCodes.put("VND", "Vietnamese Dong");
        currencyCodes.put("VUV", "Vanuatu Vatu");
        currencyCodes.put("WST", "Samoan Tala");
        currencyCodes.put("XAF", "Central African CFA Franc");
        currencyCodes.put("XCD", "Eastern Caribbean Dollar");
        currencyCodes.put("XDR", "Special Drawing Rights");
        currencyCodes.put("XOF", "West African CFA Franc");
        currencyCodes.put("XPF", "CFP Franc");
        currencyCodes.put("YER", "Yemeni Rial");
        currencyCodes.put("ZAR", "South African Rand");
        currencyCodes.put("ZMW", "Zambian Kwacha");
        currencyCodes.put("ZWL", "Zimbabwean Dollar");
    }

    public String getCurrencyName(String currencyCode) {
        return currencyCodes.get(currencyCode);
    }

    public void displayCurrencyCodes() {
        currencyCodes.forEach((code, name) -> System.out.println(code + " - " + name));
    }

    public boolean isValidCurrencyCode(String currencyCode) {
        return currencyCodes.containsKey(currencyCode);
    }
}
